export const MANAGER_LOADING ='MANAGER_LOADING';
export const ADD_MANAGER ='ADD_MANAGER';
export const MANAGER_FAILED ='MANAGER_FAILED';
export const SEND_MANAGER ='SEND_MANAGER';

export const RESTAURANT_LOADING ='RESTAURANT_LOADING';
export const ADD_RESTAURANT ='ADD_RESTAURANT';
export const RESTAURANT_FAILED ='RESTAURANT_FAILED';

